services:
  - type: web
    name: fastapi-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastapi-db
          property: connectionString
    preDeployCommand: alembic upgrade head

databases:
  - name: fastapi-db
    databaseName: fastapi_db
    user: fastapi_user
    plan: free
